"""Persistence for PostgreSQL in production and SQLite during local development."""

from __future__ import annotations

import json
import sqlite3
import time
import uuid
from typing import Any


class ConnectionAdapter:
    """Expose the small sqlite-style API used by the domain layer on both drivers."""

    def __init__(self, raw: Any, dialect: str):
        self.raw = raw
        self.dialect = dialect

    def __enter__(self) -> "ConnectionAdapter":
        self.raw.__enter__()
        return self

    def __exit__(self, exc_type: Any, exc: Any, traceback: Any) -> Any:
        result = self.raw.__exit__(exc_type, exc, traceback)
        if self.dialect == "sqlite":
            self.raw.close()
        return result

    def execute(self, sql: str, parameters: tuple[Any, ...] = ()) -> Any:
        if self.dialect == "postgresql":
            if sql.strip().upper() == "BEGIN IMMEDIATE":
                return None
            sql = sql.replace("?", "%s")
        return self.raw.execute(sql, parameters)

    def executescript(self, sql: str) -> None:
        if self.dialect == "sqlite":
            self.raw.executescript(sql)
            return
        self.raw.execute(sql)


def now_ms() -> int:
    return int(time.time() * 1000)


def compact(values: dict[str, Any]) -> dict[str, Any]:
    """ThingsBoard telemetry values must be flat and must not contain null."""
    return {key: value for key, value in values.items() if value is not None}


class DomainError(Exception):
    def __init__(self, status_code: int, detail: str):
        super().__init__(detail)
        self.status_code = status_code
        self.detail = detail


class Database:
    def __init__(self, database_url: str, ai_threshold: float):
        self.database_url = database_url
        self.ai_threshold = ai_threshold
        self.dialect = (
            "postgresql" if database_url.startswith(("postgresql://", "postgres://"))
            else "sqlite"
        )
        if self.dialect == "sqlite":
            raw_path = database_url.removeprefix("sqlite:///")
            from pathlib import Path

            self.path = Path(raw_path)
        else:
            self.path = None

    @property
    def description(self) -> str:
        if self.dialect == "postgresql":
            return "postgresql"
        return str(self.path)

    def connect(self) -> ConnectionAdapter:
        if self.dialect == "postgresql":
            try:
                import psycopg
                from psycopg.rows import dict_row
            except ImportError as exc:
                raise RuntimeError(
                    "PostgreSQL requires psycopg. Run: pip install -r requirements.txt"
                ) from exc
            connection = psycopg.connect(self.database_url, row_factory=dict_row)
            return ConnectionAdapter(connection, self.dialect)

        assert self.path is not None
        connection = sqlite3.connect(self.path, timeout=10)
        connection.row_factory = sqlite3.Row
        connection.execute("PRAGMA foreign_keys = ON")
        connection.execute("PRAGMA busy_timeout = 10000")
        return ConnectionAdapter(connection, self.dialect)

    def initialize(self) -> None:
        if self.path is not None:
            self.path.parent.mkdir(parents=True, exist_ok=True)
        with self.connect() as connection:
            if self.dialect == "sqlite":
                connection.execute("PRAGMA journal_mode = WAL")
                connection.execute("PRAGMA synchronous = FULL")
            connection.executescript(
                self._schema_sql()
            )
            timestamp = now_ms()
            connection.execute(
                """
                INSERT INTO products (
                    barcode, sku, name, vision_class, price_vnd,
                    expected_weight_g, weight_tolerance_g, active,
                    created_at_ms, updated_at_ms
                ) VALUES (?, ?, ?, ?, ?, ?, ?, 1, ?, ?)
                ON CONFLICT(barcode) DO UPDATE SET
                    sku = excluded.sku,
                    name = excluded.name,
                    vision_class = excluded.vision_class,
                    updated_at_ms = excluded.updated_at_ms
                """,
                (
                    "8935005801135",
                    "lavie_500ml",
                    "La Vie 500 ml",
                    "lavie_500ml",
                    None,
                    None,
                    None,
                    timestamp,
                    timestamp,
                ),
            )

    def _schema_sql(self) -> str:
        identity = (
            "INTEGER PRIMARY KEY AUTOINCREMENT"
            if self.dialect == "sqlite"
            else "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
        )
        large_integer = "INTEGER" if self.dialect == "sqlite" else "BIGINT"
        return f"""
                CREATE TABLE IF NOT EXISTS products (
                    id {identity},
                    barcode TEXT NOT NULL UNIQUE,
                    sku TEXT NOT NULL UNIQUE,
                    name TEXT NOT NULL,
                    vision_class TEXT NOT NULL,
                    price_vnd INTEGER,
                    expected_weight_g REAL,
                    weight_tolerance_g REAL,
                    active INTEGER NOT NULL DEFAULT 1 CHECK(active IN (0, 1)),
                    created_at_ms {large_integer} NOT NULL,
                    updated_at_ms {large_integer} NOT NULL
                );

                CREATE TABLE IF NOT EXISTS shopping_sessions (
                    id TEXT PRIMARY KEY,
                    status TEXT NOT NULL CHECK(status IN ('active', 'completed', 'cancelled')),
                    started_at_ms {large_integer} NOT NULL,
                    ended_at_ms {large_integer}
                );

                CREATE TABLE IF NOT EXISTS sensor_events (
                    id {identity},
                    session_id TEXT,
                    source TEXT NOT NULL,
                    event_type TEXT NOT NULL,
                    barcode TEXT,
                    ai_class TEXT,
                    ai_confidence REAL,
                    weight_g REAL,
                    delta_weight_g REAL,
                    decision TEXT,
                    metadata_json TEXT NOT NULL DEFAULT '{{}}',
                    created_at_ms {large_integer} NOT NULL,
                    FOREIGN KEY(session_id) REFERENCES shopping_sessions(id)
                );

                CREATE TABLE IF NOT EXISTS cart_items (
                    session_id TEXT NOT NULL,
                    product_id {large_integer} NOT NULL,
                    quantity INTEGER NOT NULL CHECK(quantity >= 0),
                    unit_price_vnd INTEGER NOT NULL DEFAULT 0,
                    updated_at_ms {large_integer} NOT NULL,
                    PRIMARY KEY(session_id, product_id),
                    FOREIGN KEY(session_id) REFERENCES shopping_sessions(id),
                    FOREIGN KEY(product_id) REFERENCES products(id)
                );

                CREATE TABLE IF NOT EXISTS cart_events (
                    id {identity},
                    session_id TEXT NOT NULL,
                    action TEXT NOT NULL CHECK(action IN ('add', 'remove')),
                    product_id {large_integer},
                    barcode TEXT NOT NULL,
                    ai_class TEXT NOT NULL,
                    ai_confidence REAL NOT NULL,
                    delta_weight_g REAL NOT NULL,
                    weight_source TEXT NOT NULL,
                    quantity_delta INTEGER NOT NULL,
                    decision TEXT NOT NULL CHECK(decision IN ('accepted', 'rejected')),
                    reasons_json TEXT NOT NULL DEFAULT '[]',
                    created_at_ms {large_integer} NOT NULL,
                    FOREIGN KEY(session_id) REFERENCES shopping_sessions(id),
                    FOREIGN KEY(product_id) REFERENCES products(id)
                );

                CREATE TABLE IF NOT EXISTS thingsboard_outbox (
                    id {identity},
                    reference_type TEXT NOT NULL,
                    reference_id TEXT NOT NULL,
                    telemetry_json TEXT NOT NULL,
                    status TEXT NOT NULL DEFAULT 'pending'
                        CHECK(status IN ('pending', 'sent')),
                    attempts INTEGER NOT NULL DEFAULT 0,
                    next_attempt_at_ms {large_integer} NOT NULL,
                    last_error TEXT,
                    created_at_ms {large_integer} NOT NULL,
                    sent_at_ms {large_integer}
                );

                CREATE INDEX IF NOT EXISTS idx_sensor_events_session_time
                    ON sensor_events(session_id, created_at_ms DESC);
                CREATE INDEX IF NOT EXISTS idx_cart_events_session_time
                    ON cart_events(session_id, created_at_ms DESC);
                CREATE INDEX IF NOT EXISTS idx_outbox_pending
                    ON thingsboard_outbox(status, next_attempt_at_ms);
                """

    @staticmethod
    def _queue_telemetry(
        connection: ConnectionAdapter,
        reference_type: str,
        reference_id: str | int,
        timestamp_ms: int,
        values: dict[str, Any],
    ) -> None:
        payload = {"ts": timestamp_ms, "values": compact(values)}
        connection.execute(
            """
            INSERT INTO thingsboard_outbox (
                reference_type, reference_id, telemetry_json,
                next_attempt_at_ms, created_at_ms
            ) VALUES (?, ?, ?, ?, ?)
            """,
            (
                reference_type,
                str(reference_id),
                json.dumps(payload, ensure_ascii=False, separators=(",", ":")),
                timestamp_ms,
                timestamp_ms,
            ),
        )

    def list_products(self) -> list[dict[str, Any]]:
        with self.connect() as connection:
            rows = connection.execute(
                "SELECT * FROM products ORDER BY name"
            ).fetchall()
        return [dict(row) for row in rows]

    def upsert_product(self, product: dict[str, Any]) -> dict[str, Any]:
        timestamp = now_ms()
        with self.connect() as connection:
            connection.execute(
                """
                INSERT INTO products (
                    barcode, sku, name, vision_class, price_vnd,
                    expected_weight_g, weight_tolerance_g, active,
                    created_at_ms, updated_at_ms
                ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
                ON CONFLICT(barcode) DO UPDATE SET
                    sku = excluded.sku,
                    name = excluded.name,
                    vision_class = excluded.vision_class,
                    price_vnd = excluded.price_vnd,
                    expected_weight_g = excluded.expected_weight_g,
                    weight_tolerance_g = excluded.weight_tolerance_g,
                    active = excluded.active,
                    updated_at_ms = excluded.updated_at_ms
                """,
                (
                    product["barcode"],
                    product["sku"],
                    product["name"],
                    product["vision_class"],
                    product.get("price_vnd"),
                    product.get("expected_weight_g"),
                    product.get("weight_tolerance_g"),
                    int(product.get("active", True)),
                    timestamp,
                    timestamp,
                ),
            )
            row = connection.execute(
                "SELECT * FROM products WHERE barcode = ?", (product["barcode"],)
            ).fetchone()
        return dict(row)

    def create_session(self) -> dict[str, Any]:
        session_id = str(uuid.uuid4())
        timestamp = now_ms()
        with self.connect() as connection:
            connection.execute(
                "INSERT INTO shopping_sessions (id, status, started_at_ms) VALUES (?, 'active', ?)",
                (session_id, timestamp),
            )
            self._queue_telemetry(
                connection,
                "shopping_session",
                session_id,
                timestamp,
                {
                    "event_type": "session_started",
                    "session_id": session_id,
                },
            )
        return {"id": session_id, "status": "active", "started_at_ms": timestamp}

    def latest_active_session(self) -> dict[str, Any]:
        """Return the newest active session for the single-cart prototype flow."""
        with self.connect() as connection:
            row = connection.execute(
                """
                SELECT *
                FROM shopping_sessions
                WHERE status = 'active'
                ORDER BY started_at_ms DESC
                LIMIT 1
                """
            ).fetchone()
        if row is None:
            raise DomainError(404, "Chua co phien mua hang dang hoat dong")
        return dict(row)

    def _require_active_session(
        self, connection: ConnectionAdapter, session_id: str
    ) -> Any:
        row = connection.execute(
            "SELECT * FROM shopping_sessions WHERE id = ?", (session_id,)
        ).fetchone()
        if row is None:
            raise DomainError(404, "Khong tim thay phien mua hang")
        if row["status"] != "active":
            raise DomainError(409, "Phien mua hang khong con hoat dong")
        return row

    def complete_session(self, session_id: str) -> dict[str, Any]:
        timestamp = now_ms()
        with self.connect() as connection:
            connection.execute("BEGIN IMMEDIATE")
            self._require_active_session(connection, session_id)
            connection.execute(
                "UPDATE shopping_sessions SET status = 'completed', ended_at_ms = ? WHERE id = ?",
                (timestamp, session_id),
            )
            cart = self._cart_snapshot(connection, session_id)
            self._queue_telemetry(
                connection,
                "shopping_session",
                session_id,
                timestamp,
                {
                    "event_type": "session_completed",
                    "session_id": session_id,
                    "cart_quantity": cart["total_quantity"],
                    "cart_total_vnd": cart["total_vnd"],
                },
            )
        return {
            "id": session_id,
            "status": "completed",
            "ended_at_ms": timestamp,
            "cart": cart,
        }

    def record_sensor_event(self, event: dict[str, Any]) -> dict[str, Any]:
        timestamp = event.get("created_at_ms") or now_ms()
        with self.connect() as connection:
            if event.get("session_id"):
                self._require_active_session(connection, event["session_id"])
            cursor = connection.execute(
                """
                INSERT INTO sensor_events (
                    session_id, source, event_type, barcode, ai_class,
                    ai_confidence, weight_g, delta_weight_g, decision,
                    metadata_json, created_at_ms
                ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
                RETURNING id
                """,
                (
                    event.get("session_id"),
                    event["source"],
                    event["event_type"],
                    event.get("barcode"),
                    event.get("ai_class"),
                    event.get("ai_confidence"),
                    event.get("weight_g"),
                    event.get("delta_weight_g"),
                    event.get("decision"),
                    json.dumps(event.get("metadata", {}), ensure_ascii=False),
                    timestamp,
                ),
            )
            event_id = int(cursor.fetchone()["id"])
            self._queue_telemetry(
                connection,
                "sensor_event",
                event_id,
                timestamp,
                {
                    "event_id": event_id,
                    "session_id": event.get("session_id"),
                    "source": event["source"],
                    "event_type": event["event_type"],
                    "barcode": event.get("barcode"),
                    "ai_class": event.get("ai_class"),
                    "ai_confidence": event.get("ai_confidence"),
                    "weight_g": event.get("weight_g"),
                    "delta_weight_g": event.get("delta_weight_g"),
                    "decision": event.get("decision"),
                },
            )
        return {"id": event_id, **event, "created_at_ms": timestamp}

    def list_sensor_events(self, limit: int) -> list[dict[str, Any]]:
        with self.connect() as connection:
            rows = connection.execute(
                "SELECT * FROM sensor_events ORDER BY id DESC LIMIT ?", (limit,)
            ).fetchall()
        result = []
        for row in rows:
            item = dict(row)
            item["metadata"] = json.loads(item.pop("metadata_json"))
            result.append(item)
        return result

    def process_cart_decision(self, decision: dict[str, Any]) -> dict[str, Any]:
        timestamp = decision.get("created_at_ms") or now_ms()
        session_id = decision["session_id"]
        action = decision["action"]
        barcode = decision["barcode"]
        ai_class = decision["ai_class"]
        ai_confidence = float(decision["ai_confidence"])
        delta_weight_g = float(decision["delta_weight_g"])
        weight_source = decision["weight_source"]

        with self.connect() as connection:
            connection.execute("BEGIN IMMEDIATE")
            self._require_active_session(connection, session_id)
            product = connection.execute(
                "SELECT * FROM products WHERE barcode = ? AND active = 1", (barcode,)
            ).fetchone()

            reasons: list[str] = []
            if product is None:
                reasons.append("unknown_barcode")
            else:
                if ai_class != product["vision_class"]:
                    reasons.append("ai_class_mismatch")
                if ai_confidence < self.ai_threshold:
                    reasons.append("ai_confidence_below_threshold")

                expected = product["expected_weight_g"]
                tolerance = product["weight_tolerance_g"]
                if expected is not None and tolerance is not None:
                    if abs(abs(delta_weight_g) - expected) > tolerance:
                        reasons.append("weight_out_of_tolerance")

            if action == "add" and delta_weight_g <= 0:
                reasons.append("weight_direction_mismatch")
            if action == "remove" and delta_weight_g >= 0:
                reasons.append("weight_direction_mismatch")

            current_quantity = 0
            if product is not None:
                quantity_row = connection.execute(
                    "SELECT quantity FROM cart_items WHERE session_id = ? AND product_id = ?",
                    (session_id, product["id"]),
                ).fetchone()
                current_quantity = int(quantity_row["quantity"]) if quantity_row else 0
                if action == "remove" and current_quantity <= 0:
                    reasons.append("product_not_in_cart")

            accepted = not reasons
            quantity_delta = 1 if action == "add" else -1
            if accepted and product is not None:
                new_quantity = current_quantity + quantity_delta
                if new_quantity == 0:
                    connection.execute(
                        "DELETE FROM cart_items WHERE session_id = ? AND product_id = ?",
                        (session_id, product["id"]),
                    )
                else:
                    connection.execute(
                        """
                        INSERT INTO cart_items (
                            session_id, product_id, quantity,
                            unit_price_vnd, updated_at_ms
                        ) VALUES (?, ?, ?, ?, ?)
                        ON CONFLICT(session_id, product_id) DO UPDATE SET
                            quantity = excluded.quantity,
                            unit_price_vnd = excluded.unit_price_vnd,
                            updated_at_ms = excluded.updated_at_ms
                        """,
                        (
                            session_id,
                            product["id"],
                            new_quantity,
                            product["price_vnd"] or 0,
                            timestamp,
                        ),
                    )

            decision_text = "accepted" if accepted else "rejected"
            cursor = connection.execute(
                """
                INSERT INTO cart_events (
                    session_id, action, product_id, barcode, ai_class,
                    ai_confidence, delta_weight_g, weight_source,
                    quantity_delta, decision, reasons_json, created_at_ms
                ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
                RETURNING id
                """,
                (
                    session_id,
                    action,
                    product["id"] if product else None,
                    barcode,
                    ai_class,
                    ai_confidence,
                    delta_weight_g,
                    weight_source,
                    quantity_delta if accepted else 0,
                    decision_text,
                    json.dumps(reasons, ensure_ascii=False),
                    timestamp,
                ),
            )
            cart_event_id = int(cursor.fetchone()["id"])
            cart = self._cart_snapshot(connection, session_id)
            self._queue_telemetry(
                connection,
                "cart_event",
                cart_event_id,
                timestamp,
                {
                    "event_id": cart_event_id,
                    "event_type": "cart_decision",
                    "session_id": session_id,
                    "action": action,
                    "barcode": barcode,
                    "product_name": product["name"] if product else "UNKNOWN",
                    "ai_class": ai_class,
                    "ai_confidence": ai_confidence,
                    "delta_weight_g": delta_weight_g,
                    "weight_source": weight_source,
                    "decision": decision_text,
                    "rejection_reasons": ",".join(reasons) if reasons else None,
                    "cart_quantity": cart["total_quantity"],
                    "cart_total_vnd": cart["total_vnd"],
                },
            )

        return {
            "event_id": cart_event_id,
            "decision": decision_text,
            "reasons": reasons,
            "product": dict(product) if product else None,
            "cart": cart,
            "created_at_ms": timestamp,
        }

    def _cart_snapshot(
        self, connection: ConnectionAdapter, session_id: str
    ) -> dict[str, Any]:
        rows = connection.execute(
            """
            SELECT
                p.barcode, p.sku, p.name, p.vision_class,
                ci.quantity, ci.unit_price_vnd,
                ci.quantity * ci.unit_price_vnd AS line_total_vnd
            FROM cart_items ci
            JOIN products p ON p.id = ci.product_id
            WHERE ci.session_id = ? AND ci.quantity > 0
            ORDER BY p.name
            """,
            (session_id,),
        ).fetchall()
        items = [dict(row) for row in rows]
        return {
            "session_id": session_id,
            "items": items,
            "total_quantity": sum(int(item["quantity"]) for item in items),
            "total_vnd": sum(int(item["line_total_vnd"]) for item in items),
        }

    def cart_snapshot(self, session_id: str) -> dict[str, Any]:
        with self.connect() as connection:
            row = connection.execute(
                "SELECT 1 FROM shopping_sessions WHERE id = ?", (session_id,)
            ).fetchone()
            if row is None:
                raise DomainError(404, "Khong tim thay phien mua hang")
            return self._cart_snapshot(connection, session_id)

    def fetch_pending_outbox(self, limit: int = 20) -> list[dict[str, Any]]:
        with self.connect() as connection:
            rows = connection.execute(
                """
                SELECT * FROM thingsboard_outbox
                WHERE status = 'pending' AND next_attempt_at_ms <= ?
                ORDER BY id
                LIMIT ?
                """,
                (now_ms(), limit),
            ).fetchall()
        return [dict(row) for row in rows]

    def mark_outbox_sent(self, outbox_id: int) -> None:
        with self.connect() as connection:
            connection.execute(
                """
                UPDATE thingsboard_outbox
                SET status = 'sent', attempts = attempts + 1,
                    sent_at_ms = ?, last_error = NULL
                WHERE id = ?
                """,
                (now_ms(), outbox_id),
            )

    def mark_outbox_retry(self, outbox_id: int, attempts: int, error: str) -> None:
        delay_seconds = min(300, 2 ** min(attempts, 8))
        with self.connect() as connection:
            connection.execute(
                """
                UPDATE thingsboard_outbox
                SET attempts = attempts + 1,
                    next_attempt_at_ms = ?, last_error = ?
                WHERE id = ?
                """,
                (now_ms() + delay_seconds * 1000, error[:500], outbox_id),
            )

    def outbox_status(self) -> dict[str, Any]:
        with self.connect() as connection:
            rows = connection.execute(
                """
                SELECT status, COUNT(*) AS count
                FROM thingsboard_outbox
                GROUP BY status
                """
            ).fetchall()
            last_error_row = connection.execute(
                """
                SELECT last_error, attempts, created_at_ms
                FROM thingsboard_outbox
                WHERE last_error IS NOT NULL
                ORDER BY id DESC LIMIT 1
                """
            ).fetchone()
        counts = {"pending": 0, "sent": 0}
        counts.update({row["status"]: row["count"] for row in rows})
        return {
            **counts,
            "last_error": dict(last_error_row) if last_error_row else None,
        }
