/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: [
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        primary: '#0D47A1',
        'primary-container': '#E3F2FD',
        'on-primary': '#ffffff',
        'on-primary-container': '#0D47A1',
        'primary-fixed': '#E3F2FD',
        'primary-fixed-dim': '#BBDEFB',
        'on-primary-fixed': '#002171',
        'on-primary-fixed-variant': '#0D47A1',
        secondary: '#5d5f5f',
        'secondary-container': '#e2e3e2',
        'on-secondary': '#ffffff',
        'on-secondary-container': '#636565',
        'secondary-fixed': '#e2e3e2',
        'secondary-fixed-dim': '#c6c7c6',
        surface: '#F8F9FA',
        'surface-dim': '#e0e0e0',
        'surface-bright': '#FFFFFF',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f4f6f9',
        'surface-container': '#e8eef6',
        'surface-container-high': '#e3f2fd',
        'surface-container-highest': '#d0e1fd',
        'surface-variant': '#e1e2ec',
        'on-surface': '#1A1A1A',
        'on-surface-variant': '#666666',
        'inverse-surface': '#1A1A1A',
        'inverse-on-surface': '#f0f0fb',
        outline: '#737785',
        'outline-variant': '#E0E0E0',
        success: '#2E7D32',
        warning: '#F59E0B',
        danger: '#D32F2F',
        error: '#D32F2F',
        'error-container': '#FFEBEE',
        'on-error': '#ffffff',
        'on-error-container': '#93000a',
        'chart-blue': '#0D47A1',
        'chart-teal': '#00C853',
        'chart-indigo': '#1565C0',
        'chart-gray': '#94A3B8',
        background: '#F8F9FA',
        'on-background': '#1A1A1A',
      },
      spacing: {
        'sidebar-width': '260px',
        'topbar-height': '64px',
        'gutter-md': '24px',
        'card-gap': '20px',
        'table-row-height': '52px',
      },
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.5rem',
        sm: '0.25rem',
        md: '0.75rem',
        lg: '1rem',
        xl: '1.5rem',
        full: '9999px',
      },
    },
  },
  plugins: [],
};
