/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: [
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        primary: '#0040a1',
        'primary-container': '#0056d2',
        'on-primary': '#ffffff',
        'on-primary-container': '#ccd8ff',
        'primary-fixed': '#dae2ff',
        'primary-fixed-dim': '#b2c5ff',
        'on-primary-fixed': '#001847',
        'on-primary-fixed-variant': '#0040a1',
        secondary: '#5d5f5f',
        'secondary-container': '#e2e3e2',
        'on-secondary': '#ffffff',
        'on-secondary-container': '#636565',
        'secondary-fixed': '#e2e3e2',
        'secondary-fixed-dim': '#c6c7c6',
        surface: '#faf8ff',
        'surface-dim': '#d9d9e4',
        'surface-bright': '#faf8ff',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f2f3fe',
        'surface-container': '#ededf8',
        'surface-container-high': '#e7e7f2',
        'surface-container-highest': '#e1e2ec',
        'surface-variant': '#e1e2ec',
        'on-surface': '#191b23',
        'on-surface-variant': '#424654',
        'inverse-surface': '#2e3038',
        'inverse-on-surface': '#f0f0fb',
        outline: '#737785',
        'outline-variant': '#c3c6d6',
        success: '#22C55E',
        warning: '#F59E0B',
        danger: '#EF4444',
        error: '#ba1a1a',
        'error-container': '#ffdad6',
        'on-error': '#ffffff',
        'on-error-container': '#93000a',
        'chart-blue': '#3B82F6',
        'chart-teal': '#14B8A6',
        'chart-indigo': '#6366F1',
        'chart-gray': '#94A3B8',
        background: '#faf8ff',
        'on-background': '#191b23',
      },
      spacing: {
        'sidebar-width': '260px',
        'topbar-height': '64px',
        'gutter-md': '24px',
        'card-gap': '20px',
        'table-row-height': '52px',
      },
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.5rem',
        sm: '0.25rem',
        md: '0.75rem',
        lg: '1rem',
        xl: '1.5rem',
        full: '9999px',
      },
    },
  },
  plugins: [],
};
