-- ==========================================================
-- SCRIPT KHỞI TẠO DATABASE CHUẨN THEO TÀI LIỆU BÀN GIAO & ERD
-- Hệ thống Smart Retail Cart (PostgreSQL)
-- ==========================================================

-- 1. Bảng products
CREATE TABLE IF NOT EXISTS products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    barcode TEXT UNIQUE NOT NULL,
    sku TEXT,
    name TEXT NOT NULL,
    vision_class TEXT,
    price_vnd INTEGER NOT NULL,
    expected_weight_g REAL DEFAULT 0,
    weight_tolerance_g REAL DEFAULT 0,
    active INTEGER DEFAULT 1,
    created_at_ms BIGINT NOT NULL,
    updated_at_ms BIGINT NOT NULL
);

-- 2. Bảng shopping_sessions
CREATE TABLE IF NOT EXISTS shopping_sessions (
    id TEXT PRIMARY KEY,
    status TEXT NOT NULL DEFAULT 'active',
    started_at_ms BIGINT NOT NULL,
    ended_at_ms BIGINT
);

-- 3. Bảng cart_items
CREATE TABLE IF NOT EXISTS cart_items (
    session_id TEXT NOT NULL REFERENCES shopping_sessions(id) ON DELETE CASCADE,
    product_id BIGINT NOT NULL REFERENCES products(id) ON DELETE CASCADE,
    quantity INTEGER NOT NULL DEFAULT 1,
    unit_price_vnd INTEGER NOT NULL,
    updated_at_ms BIGINT NOT NULL,
    PRIMARY KEY (session_id, product_id)
);

-- 4. Bảng cart_events
CREATE TABLE IF NOT EXISTS cart_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id TEXT REFERENCES shopping_sessions(id) ON DELETE SET NULL,
    action TEXT NOT NULL, -- 'add' hoặc 'remove'
    product_id BIGINT REFERENCES products(id) ON DELETE SET NULL,
    barcode TEXT,
    ai_class TEXT,
    ai_confidence REAL,
    delta_weight_g REAL,
    weight_source TEXT,
    quantity_delta INTEGER DEFAULT 1,
    decision TEXT,
    reasons_json TEXT,
    created_at_ms BIGINT NOT NULL
);

-- 5. Bảng sensor_events
CREATE TABLE IF NOT EXISTS sensor_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id TEXT REFERENCES shopping_sessions(id) ON DELETE SET NULL,
    source TEXT,
    event_type TEXT,
    barcode TEXT,
    ai_class TEXT,
    ai_confidence REAL,
    weight_g REAL,
    delta_weight_g REAL,
    decision TEXT,
    metadata_json TEXT,
    created_at_ms BIGINT NOT NULL
);

-- 6. Bảng thingsboard_outbox
CREATE TABLE IF NOT EXISTS thingsboard_outbox (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reference_type TEXT,
    reference_id TEXT,
    telemetry_json TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'pending',
    attempts INTEGER DEFAULT 0,
    next_attempt_at_ms BIGINT,
    last_error TEXT,
    created_at_ms BIGINT NOT NULL,
    sent_at_ms BIGINT
);

-- ==========================================================
-- NẠP 4 SẢN PHẨM THỬ NGHIỆM CHÍNH THỨC (MỤC 7 TÀI LIỆU BÀN GIAO)
-- ==========================================================
INSERT INTO products (barcode, sku, name, vision_class, price_vnd, expected_weight_g, weight_tolerance_g, active, created_at_ms, updated_at_ms)
VALUES 
    ('8935005801135', 'lavie_500ml', 'La Vie 500 ml', 'lavie_500ml', 10000, 500.0, 20.0, 1, 1788746300000, 1788746300000),
    ('6975493200982', 'banh_sua_chua_20g', 'Bánh Sữa Chua 20g', 'banh_sua_chua_20g', 3000, 20.0, 5.0, 1, 1788746300000, 1788746300000),
    ('8938556329004', 'pocari_sweat_500ml', 'Pocari Sweat 500 ml', 'pocari_sweat_500ml', 15000, 500.0, 20.0, 1, 1788746300000, 1788746300000),
    ('8936154640613', 'siro_ho_euca_super_extra_125ml', 'Siro EUCA Super Extra 125 ml', 'siro_ho_euca_super_extra_125ml', 60000, 150.0, 15.0, 1, 1788746300000, 1788746300000)
ON CONFLICT (barcode) DO UPDATE SET
    sku = EXCLUDED.sku,
    name = EXCLUDED.name,
    vision_class = EXCLUDED.vision_class,
    price_vnd = EXCLUDED.price_vnd,
    expected_weight_g = EXCLUDED.expected_weight_g,
    weight_tolerance_g = EXCLUDED.weight_tolerance_g,
    active = EXCLUDED.active,
    updated_at_ms = EXCLUDED.updated_at_ms;
